apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  annotations:
    # Use Nginx ingress controller for example.
    # Replace with specific annotations for your cloud provider (e.g., OKE)
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          # Frontend service
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service # Ensure this matches your Helm rendered service name (e.g., frontend-myrelease)
                port:
                  number: 80 # Frontend service port
          # API Gateway service
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: backend-service # Ensure this matches your Helm rendered service name (e.g., backend-myrelease)
                port:
                  number: 80 # API Gateway service port
